export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_COMMENTS_BY_LEAD = "GET_COMMENTS_BY_LEAD";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_BY_USER = "GET_COMMENTS_BY_USER";
export const GET_COMMENTS_BY_STORE = "GET_COMMENTS_BY_STORE";
export const GET_COMMENT = "GET_COMMENT";

// Utils
export const CLEAR_STATE = "CLEAR_STATE";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

// Leads
export const GET_LEADS = "GET_LEADS";
export const GET_LEAD = "GET_LEAD";
export const CLEAR_CURRENT_LEAD = "CLEAR_CURRENT_LEAD";
export const UPDATE_LEAD = "UPDATE_LEAD";

// Activity
// Activities
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const GET_ACTIVITIES_BY_USER = 'GET_ACTIVITIES_BY_USER';
export const GET_ACTIVITIES_BY_LEAD = 'GET_ACTIVITIES_BY_STORE';
export const GET_ACTIVITIES_AR = 'GET_ACTIVITIES_AR';

// Charts
export const GET_TOTALS_DASHBOARD = 'GET_TOTALS_DASHBOARD';

// Appointments
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const GET_APPOINTMENTS_BY_USER = 'GET_APPOINTMENTS_BY_USER';
export const GET_APPOINTMENTS_BY_STORE = 'GET_APPOINTMENTS_BY_STORE';
export const GET_APPOINTMENTS_AR = 'GET_APPOINTMENTS_AR';